services:
  localstack:
    image: localstack/localstack-pro 
    ports: 
      - "4566:4566"            # LocalStack Gateway
      ## uncomment above this line for pro version
    environment:
      - SERVICES=rds,secretsmanager,lambda,ec2,kms,iam,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - ENFORCE_IAM=0
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      start_period: 10s
  terraform:
    image: hashicorp/terraform
    entrypoint: []
    depends_on:
      localstack:
        condition: service_healthy
    command:
      - sh 
      - -c
      - "sleep infinity"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    volumes:
      - ..:/src
networks: 
  default: 
    name: localstack-network

